/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example.vava;

public class App {
    public static void main(String... args) {
        System.out.println("Lajos: " + hu.komdat.parkolasservice.models.Pet.class.getName());
    }
}
